all : 10-1 10-2 10-3 

10-1: 10-1.o
	g++ -Wall -o 10-1 10-1.o
10-1.o: 10-1.cpp
	g++ -Wall -c 10-1.cpp

10-2: 10-2.o
	g++ -Wall -o 10-2 10-2.o
10-2.o: 10-2.cpp
	g++ -Wall -c 10-2.cpp

10-3: 10-3.o
	g++ -Wall -o 10-3 10-3.o
10-3.o: 10-3.cpp
	g++ -Wall -c 10-3.cpp

clean: 
	rm -f all *.o